/// Flutter icons DeveloperIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeveloperIcons
///      fonts:
///       - asset: fonts/DeveloperIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DeveloperIcons {
  DeveloperIcons._();

  static const _kFontFam = 'DeveloperIcons';
  static const String? _kFontPkg = null;

  static const IconData gallery = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_alt = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_return = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_import_45 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout6 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_code = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse_45 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData processor = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_alt = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_horizontal = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server_alt = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server_alt2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sim = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_frame = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_vice_versa_alt = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usb = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_terminal = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData window_code = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_curve = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_doble_slash_vertical = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_dot_down = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_double_slash = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_double = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_code = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData braces_alt = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_code = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_login = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_logout = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_scroll = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_branches = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_merge = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube_skeleton = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_plus = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots3 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exc_octa = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exc_triangle = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_structure = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_text = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
